// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("Petabridge")]
[assembly: AssemblyCopyrightAttribute("Copyright © Petabridge, LLC 2015")]
[assembly: AssemblyVersionAttribute("1.1.16.0")]
[assembly: AssemblyFileVersionAttribute("1.1.16.0")]
